Respect all sniffs when reviewing PHP_CodeSniffer itself
PHPCSStandards/PHP_CodeSniffer pull request #122
Opened 2023-12-04 16:17 UTC by fredden

## Description
This is a re-creation of https://github.com/squizlabs/PHP_CodeSniffer/pull/3914

While working on another task, I noticed that warnings are ignored by default. This seems unintentional. Some discussion regarding this has taken place in https://github.com/squizlabs/PHP_CodeSniffer/pull/3914

## Suggested changelog entry
Respect warnings as well as errors from sniffs within the coding standard for PHP_CodeSniffer itself.

## Types of changes
- Bug fix _(non-breaking change which fixes an issue)_

## PR checklist
- [x] I have checked there is no other PR open for the same change.
- [x] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md).
- [x] I grant the project the right to include and distribute the code under the BSD-3-Clause license (and I have the right to grant these rights).
- [x] I have verified that the code complies with the projects coding standards.

2023-12-04 16:33 UTC, jrfnl requested changes
@fredden Thanks for porting this over. In its current state (with only one remark, I'm okay to accept this).

Note: further changes to the ruleset used by PHPCS are not my current priority. If anything, I'll likely want to standardize on something closer to [PHPCSDevCS](https://github.com/PHPCSStandards/PHPCSDevCS) at some point in the future.

2023-12-04 16:33 UTC, jrfnl commented on src/Util/Tokens.php
> +     * @see https://www.php.net/language.constants.predefined PHP Manual on magic constants
I'd rather keep this at the correct tag (`@link`) than change it just too satisfy an outdated sniff. Could you please add an exception instead ?

2023-12-05 12:58 UTC, jrfnl approved these changes

2023-12-05 12:58 UTC, merged

2023-12-05 14:10 UTC, fredden commented
> If anything, I'll likely want to standardize on something closer to [PHPCSDevCS](https://github.com/PHPCSStandards/PHPCSDevCS) at some point in the future.

I made a start on this. I got to the point where the standard is installed and runs successfully. The next step involves changing nearly every file in the repository. I've put it down for now. Would a draft pull request be valuable? I can trivially open this as a reminder / TODO item if you'd like.

2023-12-05 14:20 UTC, jrfnl commented
> > If anything, I'll likely want to standardize on something closer to [PHPCSDevCS](https://github.com/PHPCSStandards/PHPCSDevCS) at some point in the future.
> 
> I made a start on this. I got to the point where the standard is installed and runs successfully. The next step involves changing nearly every file in the repository. I've put it down for now. Would a draft pull request be valuable? I can trivially open this as a reminder / TODO item if you'd like.

Sorry, while I appreciate what you are trying to do, this is definitely *not* a priority at this moment and not something I want to spend time on at this time.

An open issue to discuss a plan to get there is one thing, an open PR, draft or not, will just be closed as noise at this time.

2023-12-05 14:37 UTC, fredden commented
I agree regarding priorities. I know you have your own way of tracking backlog items; I trust that this is somewhere in that system.

For future reference, the work started here includes 09d13e39e825d51a2655ad3b5e51f167f498350d and https://github.com/PHPCSStandards/composer-installer/pull/215.

2023-12-05 14:48 UTC, jrfnl commented
> I agree regarding priorities. I know you have your own way of tracking backlog items; I trust that this is somewhere in that system.

I will be opening issues for most of those ideas/plans/backlog I see, #105, #106, #120 and some older issues ported over from the Squizlabs repo as just the start of that, but 3.8.0 needs to get released first. The rest can wait and is just a distraction at this moment.