[Documentation] PSR12 - Opening Brace Space
PHPCSStandards/PHP_CodeSniffer pull request #171
Opened 2023-12-16 09:32 UTC by dingo-d

The PR contains the documentation for the PSR12/Classes/OpeningBraceSpace sniff.

## Description

This PR will add the documentation for the above-mentioned sniff, according to the [official standard definitions](https://www.php-fig.org/psr/psr-12/#41-extends-and-implements).

## Suggested changelog entry

Add documentation for the PSR12 OpeningBraceSpace sniff

## Related issues/external references

Part of #148

## Types of changes

- [ ] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [x] Documentation improvement

## PR checklist

- [x] I have checked there is no other PR open for the same change.
- [x] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md).
- [x] I grant the project the right to include and distribute the code under the BSD-3-Clause license (and I have the right to grant these rights).
- [ ] I have added tests to cover my changes.
- [x] I have verified that the code complies with the projects coding standards.
- [ ] [Required for new sniffs] I have added XML documentation for the sniff.

2023-12-26 07:44 UTC, jrfnl requested changes
@dingo-d Thanks for writing this up. Looking good, Code comparisons, formatting etc, all good. Just two small remarks.

2023-12-26 07:44 UTC, jrfnl commented on src/Standards/PSR12/Docs/Classes/OpeningBraceSpaceStandard.xml
> +<documentation title="Opening Brace">
```suggestion
<documentation title="Opening Brace Space">
```

2023-12-26 07:44 UTC, jrfnl commented on src/Standards/PSR12/Docs/Classes/OpeningBraceSpaceStandard.xml
> +    Opening braces must not be followed by a blank line.
Same remark about the description as I left on #170 - I think the context (OO structures only) needs to be made clear.

2024-01-03 16:25 UTC, jrfnl commented on src/Standards/PSR12/Docs/Classes/OpeningBraceSpaceStandard.xml
> +    The opening braces of object-oriented constructs must not be followed by a blank line.
```suggestion
    The opening brace of an object-oriented construct must not be followed by a blank line.
```

Just wondering if this reads better ?

2024-01-04 07:47 UTC, dingo-d commented
You can squash merge this one if it's ok 🙂

2024-01-04 08:39 UTC, jrfnl approved these changes
:shipit: Thanks @dingo-d !

2024-01-04 08:40 UTC, merged