Changelog improvements remaining versions
PHPCSStandards/PHP_CodeSniffer pull request #418
Opened 2024-03-27 13:18 UTC by rodrigoprimo

## Description

This PR adds links to all issues in the remaining sections of the changelog. It also fixes a few typos. Contrary to what I did in previous PRs related to #244, here I did not read through all the text looking for typos. I only fixed the typos highlighted by my IDE as it would take a long time to read everything. I also opted to fix the typos in a separate commit that can be squashed before merging as the number of changes in this PR is much bigger than in previous PRs. I'm hoping that this will make the review process easier.

## Related issues/external references

Part of https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/244

## Types of changes

- [ ] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [x] Documentation improvement

## PR checklist

- [ ] I have checked there is no other PR open for the same change.
- [ ] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md).
- [ ] I grant the project the right to include and distribute the code under the BSD-3-Clause license (and I have the right to grant these rights).
- [x] I have added tests to cover my changes.
- [x] I have verified that the code complies with the projects coding standards.
- [x] [Required for new sniffs] I have added XML documentation for the sniff.

2024-03-28 18:07 UTC, jrfnl requested changes
Thank you @rodrigoprimo !

Aside from some issues with duplicate links in link lists (didn't we discuss those before ?), this looks good.

I've not checked each individual link. If any issues are found with those at some point in the future, a whomever finds the issue is welcome to submit a PR to fix the link ;-)

2024-03-28 18:07 UTC, jrfnl commented on CHANGELOG.md
> +[pear-20050]: https://pear.php.net/bugs/bug.php?id=20050
These all look like duplicates to me - see line 4727-4732

2024-04-01 20:02 UTC, rodrigoprimo commented
Thanks for the review, @jrfnl!

> Aside from some issues with duplicate links in link lists (didn't we discuss those before ?), this looks good.

I missed the duplicate links. I remember us discussing duplicate links in the same version, but I don't remember us discussing duplicate links across different versions. I could have inferred that, but unfortunately, I did not.

I pushed a new commit removing the duplicates.

I noticed duplicate links added in previous PRs. Would you prefer that I push a commit fixing those to this PR or create a separate PR?

2024-04-01 20:29 UTC, jrfnl commented
> I missed the duplicate links. I remember us discussing duplicate links in the same version, but I don't remember us discussing duplicate links across different versions. I could have inferred that, but unfortunately, I did not.

Well, the previous issue was already across versions as the links between Squiz and this repo were overlapping with the links to this repo only being in recent changelogs (and the links to Squiz in older changelogs).

While duplicate link definitions which have the same URL attached is not necessarily problematic, it is still not a good idea to have them, as if one is updated, but not the other, which one should be used ? (hint: the first one found will be used, but that may not be the one updated).

You may want to read up a little on markdown. These may be good starting points:
* https://daringfireball.net/projects/markdown/syntax#link
* https://www.markdownguide.org/basic-syntax/#reference-style-links

> I pushed a new commit removing the duplicates.
> 
> I noticed duplicate links added in previous PRs. Would you prefer that I push a commit fixing those to this PR or create a separate PR?

Please feel free to fix them up in this PR.

2024-04-02 15:45 UTC, rodrigoprimo commented
Thanks for the additional information, @jrfnl.

I added the new commit fixing the other duplicate links in the file and this PR is ready for a final review.

2024-04-03 00:07 UTC, jrfnl approved these changes
Thanks @rodrigoprimo ! It's great to see the changelog improved so much (via this and the other PRs) !

2024-04-03 00:08 UTC, merged