4.0 | Zend.Debug.CodeAnalyzer: remove sniff
PHPCSStandards/PHP_CodeSniffer pull request #58
Opened 2023-11-09 17:54 UTC by jrfnl

## Description
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3802:

> I have the impression that the Zend Code Analyzer tool as stand-alone tool is no longer available. Please correct me if I'm wrong.
> 
> I propose to remove the sniff which allowed for running that tool via PHPCS in PHPCS 4.0, along the same lines as was already done for external JS/CSS tools in commit ea52e7b48165edbcb96b10a0a5de04567e4d73f8.

## Suggested changelog entry
The `Zend.Debug.CodeAnalyzer` sniff has been removed

2024-01-05 23:47 UTC, jrfnl commented
@weierophinney Just checking - have you got an opinion on this proposed sniff removal ?

2024-01-17 18:16 UTC, jrfnl commented
@weierophinney Thank you for confirming what I suspected. I will go ahead and soft deprecate this in 3.9.0, hard deprecate in the last 3.x minor and remove in 4.0.

2025-03-09 19:21 UTC, jrfnl commented
Rebased without changes to get rid of the merge conflict and to check something: the build for this PR **_should_** fail as the Squiz `ruleset.xml` file still references this sniff, which would result in a "ERROR: Referenced sniff "Zend.Debug.CodeAnalyzer" does not exist." error if the ruleset is used.

If CI does not fail on this, we are missing a QA check and that needs to be addressed.

2025-03-09 21:31 UTC, jrfnl commented
> If CI does not fail on this, we are missing a QA check and that needs to be addressed.

The missing QA check is being added now via PR #868

2025-04-13 12:18 UTC, fredden requested changes
We should also remove this line:

https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/66e178b85be1d39d9556d4691f1c1b40596d99ec/src/Standards/Squiz/ruleset.xml#L31

2025-04-13 12:39 UTC, jrfnl commented
> We should also remove this line:
> 
> https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/66e178b85be1d39d9556d4691f1c1b40596d99ec/src/Standards/Squiz/ruleset.xml#L31

Exactly (that was the reason to add the QA check in #868). Local branch has already been updated, didn't push (yet) as I'd have to keep rebasing. It's included in the 4.0 line up though, so we'll get to it some time this week.

2025-04-14 14:41 UTC, fredden approved these changes

2025-04-14 15:15 UTC, rodrigoprimo approved these changes

2025-04-14 15:15 UTC, merged