Support generics in docblock
PHPCSStandards/PHP_CodeSniffer pull request #750
Opened 2024-12-02 22:56 UTC by tm1000

This supports the following:

```
    /**
	 * @param Collection<int, TelephoneNumber> $telephoneNumbers
	 */
	public function myFunction(
		Collection $telephoneNumbers,
```

Where-as before it would say that the typehint needs to be `Collection<int, TelephoneNumber>` now it will correctly deduce that the type hint needs to be `Collection` and will not return an error

I based this off of https://github.com/squizlabs/PHP_CodeSniffer/pull/708 which is similar in scope. 

~~Unfortunately I was unable to run the unit tests because I'm on PHP 8.1 and something in the code continues to try to use the function `each` which does not exist in php 8.0~~

Edit: There is now a test!

2024-12-02 22:57 UTC, tm1000 commented
Give me a moment to fix the conflicts

2024-12-02 22:58 UTC, tm1000 commented
Ref: https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/746#issuecomment-2510731312

2024-12-02 23:01 UTC, tm1000 commented
This may fail and if so I'll just have to work on this locally instead of blind through github.

2024-12-02 23:03 UTC, tm1000 commented
@jrfnl can you initiate the actions?

2024-12-03 16:28 UTC, jrfnl commented
@tm1000 Thanks for this PR. I'm starting to review it now and noticed the PR template had been removed. I've taken the liberty to restore it and would like to ask you to fill in the missing bits & pieces (and maybe verify the bits I already filled in).

2024-12-03 16:31 UTC, tm1000 commented
@jrfnl sorry about that I did a quick copy and paste. 

Also I'll need to sit down and fix the pr issues 

At least it's here now. Finally :)

2024-12-03 16:45 UTC, jrfnl commented
> @jrfnl sorry about that I did a quick copy and paste.

No worries and I appreciate you porting the PR over. 

> Also I'll need to sit down and fix the pr issues

I think the primary issue (which is failing the build) is a missing new line at the `phpcs-746.php` file.

Expanding the tests a little more would also be good, but I'll go through the PR and will leave you a review.

> At least it's here now. Finally :)

Indeed ;-)

2024-12-04 00:33 UTC, jrfnl requested changes
@tm1000 Thanks for this PR and for your willingness to contribute!

I've gone through the PR now and left a few comments inline.

Aside from that, [as I mentioned in the issue](https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/746#issuecomment-2510731312), the tests will need to be expanded a bit. I'm thinking:
* Include the other examples from the code sample in the issue (#746).
* And then have a second test with that same complete set, but then for a function which doesn't have type declarations yet. Even though the test setup as-is does not verify the _message_, having those tests there, still allows to verify (manually) that the message is now correct and also safeguards that the message _will_ be thrown in those situations.

Other than that, I'd be happy to see this go into the codebase.

2024-12-04 00:33 UTC, jrfnl commented on src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc
> +/**
Please remove this change. It doesn't belong with this PR and may have been there for a reason (as the sniff is about checking docblock formatting). Same for the fixed file.

2024-12-04 00:33 UTC, jrfnl commented on src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc
> +}// end genericType()
Please end the file on a new line char.

2024-12-14 19:32 UTC, jrfnl commented
@tm1000 Just checking in to see whether you have chance to update this PR based on the review. Would be great to get this merged.

2025-01-03 13:43 UTC, Karpec commented
Hello,

Happy New Year! I hope you're doing well. Could you let me know how things are looking with this PR? Is there any chance it might make it into the release?

Thank you!

2025-01-03 17:11 UTC, tm1000 commented
It will probably be merged when I'm
Not on vacation

Thanks for understanding! :)

2025-01-12 14:16 UTC, jrfnl commented
Oh 😂 Just ran into this issue myself somewhere...

@tm1000 Would be great if this would be ready for the next release 🙏🏻

2025-01-28 21:18 UTC, jrfnl commented
@tm1000 Just checking in again. If you don't have the time or intention to finish off this PR, please just let me know and I'll fix up the open review remarks when merging.

2025-01-28 21:46 UTC, tm1000 commented
Hey @jrfnl !

I ended up coming down with a bad case of Pneumonia so been trying to slowly recover from that and everythin is taking more time than it used to. Feel feel to do the work on this if you need it is also still in my queue for when I recover

2025-01-28 21:54 UTC, jrfnl commented
@tm1000 Oh dear, I'm sorry to hear that. Pneumonia can be nasty! Please take your time getting well. This can wait (and I normally try to avoid taking over if the OP still intends to work on the PR).

2025-03-22 11:11 UTC, jrfnl commented
@tm1000 How are things going ?

2025-04-13 02:11 UTC, jrfnl commented
Closing for lack of response to PR feedback.

@tm1000 I'd love for this PR to get into a mergable state, but as things are, I'm not seeing any progress. If/when you have the time and the willingness to update the PR per the provided feedback, the PR can be re-opened.

2025-04-13 02:11 UTC, closed without merging